'use strict';
/* Rot-Beweis: je Richtung im Helfer (gleichlaufProben, Test „·Rot-Beweis“) an einem verfälschten Schema. */
/* Gleichlauf docs/format-modul/format-modul-schema.json ↔ formatModulPruefen.
   Regeln und Begründung: tests/mit-modul/helfer/modul-schema-gleichlauf.js. */
const { gleichlaufProben } = require('./helfer/modul-schema-gleichlauf.js');

const basis = { modulTyp: 'format', moduleVersion: 1, format: 'zz-probe', richtung: 'import', leser: 'json@1',
  sektor: 'finance', label: 'Probe', sprache: 'de', zuordnung: [{ feld: 'accounts', ziel: 'x' }] };
const mit = (x) => ({ ...basis, ...x });
const ohne = (k) => { const m = { ...basis }; delete m[k]; return m; };
const xmlAus = mit({ richtung: 'export', leser: null, schreiber: 'xml@1', quelle: 'Dokument',
  zuordnung: [{ feld: 'accounts', ziel: 'Konten.Konto' }] });
const mitXml = (x) => ({ ...xmlAus, ...x });

gleichlaufProben({
  typ: 'format',
  positiv: [
    ['Eingabe mit Leser', basis],
    ['ohne richtung gilt Eingabe', ohne('richtung')],
    ['richtung null gilt Eingabe', mit({ richtung: null })],
    ['Ausgabe ohne Leser und Schreiber', mit({ richtung: 'export', leser: null })],
    ['Ausgabe mit json@1', (() => { const m = mit({ richtung: 'export', schreiber: 'json@1' }); delete m.leser; return m; })()],
    ['Ausgabe xml@1 mit Wurzel', xmlAus],
    ['Ausgabe xml@1 mit Attribut und Text', mitXml({ schreiber: ' xml@1 ', quelle: 'Wurzel.Innen',
      zuordnung: [{ feld: 'accounts', ziel: 'Konto.@nr' }, { feld: 'accounts', ziel: 'Konto.#text', alsListe: true }] })],
    ['Eingabe mit xml-fremdem Ziel und Schreiber xml@1', mit({ schreiber: 'xml@1', zuordnung: [{ feld: 'accounts', ziel: '1 x.y' }] })],
    ['mit allen Freiwilligen', mit({ akzeptiert: '', quelle: 'daten.wert', quelleWurzelFallback: true, rechtsraum: '',
      sprache: ' en-GB ', erkennen: [{ pfad: 'typ', gleich: 'x' }, { pfad: 'a.b', vorhanden: true, istObjekt: false },
        { pfad: 'c', istObjekt: true }, { pfad: 'n', gleich: 0 }, { pfad: 'w', gleich: false }],
      zuordnung: [{ feld: 'accounts', ziel: 'x', alsListe: false }] })],
    ['erkennen leer und Freiwillige null', mit({ erkennen: [], akzeptiert: null, quelle: null, rechtsraum: null, schreiber: null })],
    ['Pfad mit Leerzeichen-Teilen', mit({ quelle: ' . ' })],
    ['Einlass-Marken', mit({ appVersion: 'v1', ungeprueft: true, eingelassenAm: '2026-09-26T00:00:00Z' })],
    ['U2-ADR-465: xml@1 mit Werteabbildung und Datumsteil', mitXml({ zuordnung: [{ feld: 'accounts', ziel: 'Konto.art', werte: { a: 'A', b: 1 } },
      { bereich: 'identity', feld: 'birthDate', ziel: 'Person.jahr', teil: 'jahr' }] })],
    ['U2-ADR-465: xml@1 mit Wurzelnamen mit Punkten', (() => { const m = mitXml({ wurzel: 'fim.S99000001.00000001001000' }); delete m.quelle; return m; })()],
    ['U2-ADR-465: xml@1 mit Namensraum, zweitem Bereich und festem Wert', mitXml({ namensraum: 'urn:vivodepot:probe:1',
      zuordnung: [{ feld: 'accounts', ziel: 'Konto.nr' }, { fest: true, ziel: 'Konto.geprueft' }, { bereich: 'identity', feld: 'givenName', ziel: 'Person.vorname' }] })],
  ],
  negativ: [
    ['kein Objekt', null, 'kein-objekt'],
    ['Array', [], 'kein-objekt'],
    ['Schlüssel constructor', mit({ constructor: 1 }), 'kein-code-erlaubt'],
    ['prototype in einer Zuordnung', mit({ zuordnung: [{ feld: 'accounts', ziel: 'x', prototype: 1 }] }), 'kein-code-erlaubt'],
    ['ohne format', ohne('format'), 'format'],
    ['format leer', mit({ format: ' ' }), 'format'],
    ['ohne moduleVersion', ohne('moduleVersion'), 'moduleVersion'],
    ['moduleVersion 0', mit({ moduleVersion: 0 }), 'moduleVersion'],
    ['moduleVersion 1.5', mit({ moduleVersion: 1.5 }), 'moduleVersion'],
    ['richtung beides', mit({ richtung: 'beides' }), 'richtung'],
    ['ohne sektor', ohne('sektor'), 'sektor'],
    ['sektor leer', mit({ sektor: '' }), 'sektor'],
    ['ohne label', ohne('label'), 'label'],
    ['label leer', mit({ label: '  ' }), 'label'],
    ['label mit Tag', mit({ label: 'a<b>' }), 'kein-reiner-text'],
    ['label mit Entität', mit({ label: 'a&amp;b' }), 'kein-reiner-text'],
    ['label mit Anführungszeichen', mit({ label: 'a"b' }), 'kein-reiner-text'],
    ['ohne sprache', ohne('sprache'), 'sprache'],
    ['sprache leer', mit({ sprache: ' ' }), 'sprache'],
    ['sprache Deutsch', mit({ sprache: 'Deutsch' }), 'sprache-form'],
    ['Eingabe ohne Leser', ohne('leser'), 'leser'],
    ['Eingabe mit Leser null', mit({ leser: null }), 'leser'],
    ['Leser leer', mit({ leser: ' ' }), 'leser'],
    ['Leser Zahl', mit({ leser: 1 }), 'leser'],
    ['Ausgabe mit leerem Leser', mit({ richtung: 'export', leser: '' }), 'leser'],
    ['Schreiber leer', mit({ schreiber: '' }), 'schreiber'],
    ['Schreiber Zahl', mit({ schreiber: 1 }), 'schreiber'],
    ['akzeptiert Zahl', mit({ akzeptiert: 1 }), 'akzeptiert'],
    ['quelle leer', mit({ quelle: '' }), 'quelle'],
    ['quelle mit leerem Teil', mit({ quelle: 'a..b' }), 'quelle'],
    ['quelle mit __proto__-Teil', mit({ quelle: 'a.__proto__' }), 'quelle'],
    ['quelle Zahl', mit({ quelle: 1 }), 'quelle'],
    ['rechtsraum Zahl', mit({ rechtsraum: 1 }), 'rechtsraum'],
    ['erkennen kein Array', mit({ erkennen: { pfad: 'x', gleich: 1 } }), 'erkennen'],
    ['erkennen ohne gültigen Vergleich', mit({ erkennen: [{ pfad: 'x' }] }), 'erkennen-leer'],
    ['erkennen gleich null', mit({ erkennen: [{ pfad: 'x', gleich: null }] }), 'erkennen-leer'],
    ['erkennen fremder Schlüssel', mit({ erkennen: [{ pfad: 'x', gleich: 1, auch: 2 }] }), 'erkennen-leer'],
    ['erkennen Pfad kaputt', mit({ erkennen: [{ pfad: 'x.', gleich: 1 }] }), 'erkennen-leer'],
    ['erkennen Eintrag kein Objekt', mit({ erkennen: ['x'] }), 'erkennen-leer'],
    ['ohne zuordnung', ohne('zuordnung'), 'zuordnung'],
    ['zuordnung leer', mit({ zuordnung: [] }), 'zuordnung'],
    ['zuordnung ohne feld', mit({ zuordnung: [{ ziel: 'x' }] }), 'zuordnung-leer'],
    ['zuordnung Ziel kaputt', mit({ zuordnung: [{ feld: 'accounts', ziel: '.x' }] }), 'zuordnung-leer'],
    ['zuordnung fremder Schlüssel', mit({ zuordnung: [{ feld: 'accounts', ziel: 'x', wie: 1 }] }), 'zuordnung-leer'],
    ['zuordnung Eintrag kein Objekt', mit({ zuordnung: [null] }), 'zuordnung-leer'],
    ['xml@1 ohne Wurzel', (() => { const m = { ...xmlAus }; delete m.quelle; return m; })(), 'schreiber-xml-ohne-wurzel'],
    ['xml@1 mit Wurzel null', mitXml({ quelle: null }), 'schreiber-xml-ohne-wurzel'],
    ['xml@1 Wurzelname mit Ziffer vorn', mitXml({ quelle: '1Dok' }), 'schreiber-xml-wurzelname'],
    ['xml@1 Wurzelname mit Leerzeichen', mitXml({ quelle: 'a b' }), 'schreiber-xml-wurzelname'],
    ['xml@1 Zielname mit Leerzeichen', mitXml({ zuordnung: [{ feld: 'accounts', ziel: 'a b' }] }), 'schreiber-xml-zielname'],
    ['xml@1 Attribut nicht am Ende', mitXml({ zuordnung: [{ feld: 'accounts', ziel: '@a.b' }] }), 'schreiber-xml-zielname'],
    ['U2-ADR-465: Namensraum ohne URI-Form', mitXml({ namensraum: 'kein uri' }), 'namensraum'],
    ['U2-ADR-465: Namensraum an json@1', (() => { const m = mit({ richtung: 'export', schreiber: 'json@1', namensraum: 'urn:vivodepot:x:1' }); delete m.leser; return m; })(), 'namensraum-ohne-xml'],
    ['U2-ADR-465: nur feste Werte', mitXml({ zuordnung: [{ fest: 'x', ziel: 'a.b' }] }), 'zuordnung-nur-fest'],
    ['U2-ADR-465: quelle und wurzel zugleich', mitXml({ wurzel: 'w' }), 'schreiber-xml-zwei-wurzeln'],
    ['U2-ADR-465: wurzel an json@1', (() => { const m = mit({ richtung: 'export', schreiber: 'json@1', wurzel: 'w' }); delete m.leser; return m; })(), 'wurzel-ohne-xml'],
    ['U2-ADR-465: hinweis mit „--“', mitXml({ hinweis: 'a -- b' }), 'hinweis'],
    ['U2-ADR-465: hinweis an json@1', (() => { const m = mit({ richtung: 'export', schreiber: 'json@1', hinweis: 'x' }); delete m.leser; return m; })(), 'hinweis-ohne-xml'],
  ],
  nurKern: {
    reserviert: 'Welche Kennungen ab Werk belegt sind, hängt an den eingebauten Ein- und Ausgabekanälen des Kerns — die Liste wächst mit dem Bestand, das Schema kennt sie nicht.',
    sektor: 'Ob ein Bereich existiert, hängt am laufenden Bereichsbestand (eingebaute und angedockte Bereiche) — das Schema prüft nur, dass eine Kennung dasteht.',
    leser: 'Ob eine Leser-Kennung auflöst, hängt an der eingebauten Lesertabelle samt früheren Kennungen — das Schema prüft nur Form und Pflicht.',
    schreiber: 'Ob eine Schreiber-Kennung auflöst, hängt an der eingebauten Schreibertabelle — das Schema prüft nur die Form.',
    'zuordnung-leer': 'Ob ein Feld im Bereich existiert, hängt am laufenden Feldbestand — der Kern verwirft unbekannte Felder einzeln; bleibt keine Zuordnung übrig, lehnt er ab.',
  },
  nurKernFaelle: [
    ['reservierte Kennung json', mit({ format: 'json' }), 'reserviert'],
    ['reservierte Ausgabe-Kennung', mit({ format: 'ics-vorsorge', richtung: 'export', leser: null }), 'reserviert'],
    ['unbekannter Bereich', mit({ sektor: 'gibtesnicht' }), 'sektor'],
    ['unbekannter Leser', mit({ leser: 'json@9' }), 'leser'],
    ['unbekannter Schreiber', mit({ schreiber: 'csv@1' }), 'schreiber'],
    ['nur unbekannte Felder', mit({ zuordnung: [{ feld: 'gibtesnicht', ziel: 'x' }] }), 'zuordnung-leer'],
  ],
});
